# criação de pod para testar o "cpu-constaints.yml"
# pod com parametros de cpu NOT OK

---
apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-demo-2
  namespace: contraints-cpu-example
spec:
  containers:
    - name: constraints-cpu-demo-2-ctr
      image: nginx
      resources:
        limits:
          cpu: "1.5"
        requests:
          cpu: "500m"