############################
##                        ##
##   FUNCTION-NODEJS.YML  ##
##                        ##
############################

# Obs: Função para rodar a função python via kubeless


---
apiVersion: kubeless.io/v1beta1
kind: Funtion
metadata:
  name: hello-nodejs
spec:
  handler: handler.hello
  runtime: nodejs6
  function: |
    module.exports = {
      hello: function(event, context){
        return 'Hello World'
      }
    }