################
##            ##
##  SECRETS   ##
##            ##
################

# obs: o Secret tem a função de tratar dados sensiveis, como usuario e senha do banco de dados

# 1# criação do secret setando os dados "username" e "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: adminRancher
type: Opaque    #torna o pod invisivel na interface
data: 
  username: dXNlcm5hbWU=    #echo -n <username> | base64
  password: cGFzc3dvcmQ=    #echo -n <password> | base64


# 2# criação do Pod redis, buscando os dados username e password referenciados acima no secret
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  image: redis
  env:
  - name: username
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: username
  - name: password
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: password
